### ISSUE TITLE
3.3.0 bug cause compressed JS error in production build

### ISSUE THREAD

**Issue by FromStoneage** [gruntjs/grunt-contrib-uglify#505]
after upgrading to 3.3.0 using **harmony** branch my production is throwing errors with the following source.
```
function m(t, e, n, i) {
                var r;
                return t.$watch(function(t) {
                    return r(),
                    i(t)
                }, e, n)
            }
```
console error below:
```
TypeError: r is not a function
    at vendor.0e71da8b.js:1
    at h.$digest (vendor.0e71da8b.js:1)
    at h.$apply (vendor.0e71da8b.js:1)
    at y (vendor.0e71da8b.js:1)
    at _ (vendor.0e71da8b.js:1)
    at XMLHttpRequest.y.onload (vendor.0e71da8b.js:1)
```

Also, please avoid rebase / rewrite history on harmony branch we use shrinkwrap to lock the specific commit of the branch but if you rewrite history specific commit are no longer relevant as they don't point to any valid hash in the repo anymore. This caused us unable to rollback to a previous stable release version. We have a hash from harmony branch 9315efca3bf977a35ce2f29ee34b00b14dafa171 no longer relevant. We also tried to rollback to previous 3.2.1 version of harmony branch still produce the same error.

**Comment by alexlamsl** [comment]
Please file issues with `uglify-es` in the upstream project, not here.

For `harmony` branch, see https://github.com/gruntjs/grunt-contrib-uglify/issues/499#issuecomment-354288623
